defaults:
  - _self_
  - data: data.yaml
  - model: model.yaml
  - train: train.yaml

project:
  name: "wandb_test"
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
  seed: 42

dirs:
  outputs: outputs/${project.timestamp}
  subdirs: ["checkpoints", "logs", "metrics"]

metrics:
  scores: ["rouge_score", "bleu_score", "f1_score", "accuracy"]


logger:
  wandb:
    project_name: ${project.name}
    entity: "ailab_upstage_fastcampus"
    tags: ["tag1"]

hydra:
  run:
    dir: ${dirs.outputs}/logs/hydra/${project.timestamp}
  output_subdir: null
  job:
    chdir: false