defaults:
  - model: efficientnet
  - data: fashion_mnist
  - train: train
  - _self_

project:
  name: "wandb_test"
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
  seed: 42

dirs:
  outputs: outputs/${project.timestamp}
  dataset: "data"
  subdirs: ["checkpoints", "logs", "metrics"]
  wandb: ${dirs.outputs}/logs/wandb

logger:
  wandb:
    project_name: ${project.name}
    entity: "ailab_upstage_fastcampus"
    job_type: "train"
    tags: ["tag1"]
    dir: ${dirs.wandb}
    reinit: true # 동일한 스크립트 내에서 여러 개의 실행(run)을 생성하고 싶을 때 reinit=True를 사용

hydra:
  run:
    dir: ${dirs.outputs}/logs/hydra
  output_subdir: null
  job:
    chdir: false