defaults:
  - model: vit
  - data: fashion_mnist
  - train: train
  - _self_

project:
  name: "test"
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
  seed: 42

logger:
  wandb:
    project_name: ${project.name}
    entity: "ailab_upstage_fastcampus"
    job_type: "train"
    tags: []
    dir: ${dirs.wandb}
    reinit: true

# Debug 모드 설정 - job_type이 debug일 때 사용될 설정
debug:
  batch_size: 16
  data_ratio: 0.1
  epochs: 2
  num_workers: 2


dirs:
  outputs: outputs/${project.timestamp}
  dataset: "data"
  models: "models"
  subdirs: ["checkpoints", "logs", "metrics"]
  wandb: ${dirs.outputs}/logs/wandb

hydra:
  run:
    dir: ${dirs.outputs}/logs/hydra
  output_subdir: null
  job:
    chdir: false