epochs: 2
lr: 0.001
save_dir: ${dirs.outputs}/checkpoints

metrics:
  train: ["accuracy", "f1", "loss"]
  val: ["accuracy", "f1", "loss"]
  learning_curve: ["accuracy", "loss"]
  
best_model:
  metric: "val/f1"
  mode: "max"

verbose_metrics: false